const texts = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Sagittis orci a scelerisque purus semper eget duis at. Suspendisse interdum consectetur libero id faucibus. Duis convallis convallis tellus id. Sit amet cursus sit amet. Consectetur purus ut faucibus pulvinar elementum. Bibendum enim facilisis gravida neque convallis a. Ut pharetra sit amet aliquam id diam maecenas ultricies. Pretium lectus quam id leo in vitae turpis massa. Non curabitur gravida arcu ac tortor dignissim. Nisl nisi scelerisque eu ultrices vitae. Cras semper auctor neque vitae tempus.",

  "Scelerisque eu ultrices vitae auctor eu augue ut. Eget mi proin sed libero enim sed faucibus. Odio euismod lacinia at quis risus sed. Ornare suspendisse sed nisi lacus sed viverra tellus. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. At urna condimentum mattis pellentesque id nibh. Arcu ac tortor dignissim convallis aenean. Hac habitasse platea dictumst vestibulum rhoncus est. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Quisque non tellus orci ac auctor augue. Magna ac placerat vestibulum lectus mauris ultrices. Vitae congue mauris rhoncus aenean vel elit. Feugiat in ante metus dictum at tempor commodo ullamcorper a.",

  "Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Sit amet facilisis magna etiam tempor orci eu lobortis. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Lobortis feugiat vivamus at augue eget arcu dictum. Sit amet nulla facilisi morbi tempus iaculis urna id. Consectetur libero id faucibus nisl tincidunt eget nullam non. Platea dictumst vestibulum rhoncus est. Volutpat est velit egestas dui. Sit amet mattis vulputate enim nulla. Vitae auctor eu augue ut lectus arcu bibendum at.",

  "Ut porttitor leo a diam sollicitudin tempor id eu. Morbi tempus iaculis urna id volutpat lacus. Orci ac auctor augue mauris augue neque. Sit amet porttitor eget dolor. Dignissim cras tincidunt lobortis feugiat. Sed turpis tincidunt id aliquet risus. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Ut morbi tincidunt augue interdum velit euismod in. Sit amet risus nullam eget. Aliquet enim tortor at auctor urna nunc id cursus metus.",

  "Lectus urna duis convallis convallis tellus id. Faucibus nisl tincidunt eget nullam non nisi. Ultricies leo integer malesuada nunc vel risus commodo. Sodales neque sodales ut etiam sit amet nisl purus in. At augue eget arcu dictum varius duis at consectetur lorem. Condimentum lacinia quis vel eros donec ac odio. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Justo laoreet sit amet cursus sit amet dictum sit. Fringilla urna porttitor rhoncus dolor purus non enim. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Nisi est sit amet facilisis magna etiam tempor orci. Lobortis scelerisque fermentum dui faucibus in.",

  "Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Cursus mattis molestie a iaculis. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Consectetur libero id faucibus nisl tincidunt eget nullam. Sit amet porttitor eget dolor morbi non arcu. Ut sem viverra aliquet eget sit amet. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Feugiat in fermentum posuere urna nec. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Blandit cursus risus at ultrices mi. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Purus faucibus ornare suspendisse sed.",

  "Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Nullam non nisi est sit amet facilisis magna etiam. Augue ut lectus arcu bibendum at varius. Elit sed vulputate mi sit amet mauris commodo. Senectus et netus et malesuada. Enim sed faucibus turpis in eu mi bibendum. Amet nisl suscipit adipiscing bibendum est ultricies integer. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Sagittis eu volutpat odio facilisis mauris sit amet. Vel eros donec ac odio tempor orci dapibus. Augue lacus viverra vitae congue eu consequat ac felis donec. Nullam eget felis eget nunc lobortis mattis aliquam.",

  "Aliquam ut porttitor leo a diam sollicitudin tempor. Cras sed felis eget velit. Risus pretium quam vulputate dignissim suspendisse. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Diam maecenas sed enim ut sem viverra aliquet eget sit. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Eros in cursus turpis massa tincidunt dui ut ornare. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Sapien faucibus et molestie ac feugiat sed. Viverra nam libero justo laoreet sit amet cursus sit. Fames ac turpis egestas maecenas pharetra convallis posuere morbi.",

  "Vulputate dignissim suspendisse in est ante in nibh. Et ultrices neque ornare aenean euismod elementum nisi. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Varius morbi enim nunc faucibus a pellentesque sit amet. Vulputate sapien nec sagittis aliquam. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Commodo nulla facilisi nullam vehicula. Bibendum enim facilisis gravida neque convallis a. Habitasse platea dictumst quisque sagittis purus sit amet. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada. In mollis nunc sed id semper risus in hendrerit. Ut ornare lectus sit amet est placerat in. Augue interdum velit euismod in pellentesque massa placerat duis. Quam nulla porttitor massa id neque aliquam vestibulum morbi. Arcu dictum varius duis at consectetur lorem. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Sit amet porttitor eget dolor morbi non arcu risus.",

  "Non nisi est sit amet facilisis. Iaculis nunc sed augue lacus viverra vitae congue. Massa placerat duis ultricies lacus sed turpis tincidunt id. In massa tempor nec feugiat nisl pretium fusce. Magna fermentum iaculis eu non diam phasellus. Turpis tincidunt id aliquet risus. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Amet justo donec enim diam vulputate ut. Ac orci phasellus egestas tellus rutrum tellus. Duis at consectetur lorem donec massa. Semper feugiat nibh sed pulvinar. Sapien et ligula ullamcorper malesuada. Egestas sed sed risus pretium quam. Pretium nibh ipsum consequat nisl vel pretium lectus quam. At varius vel pharetra vel turpis nunc eget lorem dolor. Facilisis magna etiam tempor orci eu. Bibendum at varius vel pharetra vel turpis.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar. Justo nec ultrices dui sapien eget. Leo a diam sollicitudin tempor id eu nisl nunc mi. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Massa id neque aliquam vestibulum. Lectus sit amet est placerat in egestas erat imperdiet sed. Amet justo donec enim diam vulputate ut. Eu facilisis sed odio morbi quis commodo odio. Velit dignissim sodales ut eu sem integer vitae justo. Sodales ut eu sem integer vitae justo eget.",

  "Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Pharetra vel turpis nunc eget lorem. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Amet justo donec enim diam. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Purus sit amet volutpat consequat mauris nunc congue nisi. Vitae semper quis lectus nulla at. Euismod nisi porta lorem mollis aliquam ut porttitor. Malesuada bibendum arcu vitae elementum curabitur vitae. Facilisi morbi tempus iaculis urna id volutpat. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Cursus risus at ultrices mi tempus. At risus viverra adipiscing at in. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Nulla facilisi nullam vehicula ipsum a arcu. Eu sem integer vitae justo.",

  "Posuere urna nec tincidunt praesent semper feugiat. Amet volutpat consequat mauris nunc congue nisi vitae. Arcu risus quis varius quam. Non quam lacus suspendisse faucibus interdum posuere. Erat nam at lectus urna. Massa vitae tortor condimentum lacinia quis vel eros donec. Sed egestas egestas fringilla phasellus faucibus. Non enim praesent elementum facilisis. Aliquam eleifend mi in nulla posuere. Ac turpis egestas integer eget aliquet nibh praesent. Blandit massa enim nec dui nunc mattis enim ut. Augue mauris augue neque gravida in fermentum et. Ac turpis egestas integer eget aliquet nibh praesent tristique. Aliquam etiam erat velit scelerisque in dictum. In vitae turpis massa sed elementum. Lobortis mattis aliquam faucibus purus in massa tempor nec. At volutpat diam ut venenatis tellus in metus vulputate. Viverra adipiscing at in tellus integer feugiat scelerisque.",

  "Facilisi morbi tempus iaculis urna id. Commodo odio aenean sed adipiscing. Ac turpis egestas integer eget aliquet nibh. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Blandit turpis cursus in hac habitasse platea dictumst. Ipsum nunc aliquet bibendum enim facilisis. Tortor dignissim convallis aenean et. Sit amet consectetur adipiscing elit. Id donec ultrices tincidunt arcu non. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Eget dolor morbi non arcu risus quis varius quam.",

  "Aliquet nibh praesent tristique magna sit amet purus gravida quis. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Nisl nisi scelerisque eu ultrices vitae auctor. Praesent tristique magna sit amet purus gravida. Lacus vel facilisis volutpat est velit egestas dui id. Morbi tristique senectus et netus et malesuada. Lacus vestibulum sed arcu non odio euismod. Vel facilisis volutpat est velit egestas. Sed id semper risus in. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Ultricies tristique nulla aliquet enim tortor at auctor. Blandit volutpat maecenas volutpat blandit. Tristique senectus et netus et. Ac placerat vestibulum lectus mauris ultrices eros in cursus turpis. Purus gravida quis blandit turpis cursus in hac habitasse. Vitae congue mauris rhoncus aenean vel elit. Eu non diam phasellus vestibulum lorem. Euismod nisi porta lorem mollis aliquam ut porttitor. Donec enim diam vulputate ut pharetra sit amet aliquam.",

  "Sit amet nisl suscipit adipiscing. Arcu felis bibendum ut tristique et egestas quis ipsum. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Sit amet nisl suscipit adipiscing bibendum. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Ac turpis egestas sed tempus urna et pharetra. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Euismod nisi porta lorem mollis. Et magnis dis parturient montes nascetur ridiculus mus. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Dui sapien eget mi proin sed. Non blandit massa enim nec dui nunc. Lobortis feugiat vivamus at augue eget arcu dictum. A lacus vestibulum sed arcu non odio. At volutpat diam ut venenatis tellus in metus. Eget mauris pharetra et ultrices neque ornare aenean euismod elementum. Sem et tortor consequat id porta nibh venenatis cras sed. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Integer enim neque volutpat ac tincidunt vitae semper.",

  "Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Turpis nunc eget lorem dolor. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Mattis rhoncus urna neque viverra justo. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Eu feugiat pretium nibh ipsum consequat nisl vel. Id interdum velit laoreet id donec ultrices tincidunt. Netus et malesuada fames ac turpis. Urna cursus eget nunc scelerisque viverra mauris in. Amet consectetur adipiscing elit duis. Tristique risus nec feugiat in fermentum posuere urna. Ac auctor augue mauris augue.",

  "Integer quis auctor elit sed. Pretium lectus quam id leo in vitae turpis massa sed. Donec pretium vulputate sapien nec sagittis aliquam malesuada. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Felis bibendum ut tristique et egestas quis. At erat pellentesque adipiscing commodo. Bibendum ut tristique et egestas quis. Aenean euismod elementum nisi quis. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Sed arcu non odio euismod. Fusce id velit ut tortor pretium viverra suspendisse potenti. Consequat interdum varius sit amet. Tellus cras adipiscing enim eu turpis egestas pretium.",

  "Mattis enim ut tellus elementum. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra accumsan. Leo vel orci porta non. Amet nisl suscipit adipiscing bibendum est. Aenean pharetra magna ac placerat. Vitae justo eget magna fermentum. Sed viverra ipsum nunc aliquet bibendum enim. Ipsum nunc aliquet bibendum enim. In aliquam sem fringilla ut morbi tincidunt augue interdum. Sem integer vitae justo eget magna fermentum. Amet nisl purus in mollis nunc sed.",

  "Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Ut venenatis tellus in metus. Dolor sit amet consectetur adipiscing. Enim diam vulputate ut pharetra sit amet aliquam id. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Nunc id cursus metus aliquam eleifend. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Fermentum posuere urna nec tincidunt praesent semper. Enim blandit volutpat maecenas volutpat blandit. Commodo elit at imperdiet dui. Convallis convallis tellus id interdum. Adipiscing diam donec adipiscing tristique risus nec feugiat.",

  "Sed egestas egestas fringilla phasellus faucibus scelerisque. Mattis molestie a iaculis at erat. Nisi est sit amet facilisis magna etiam tempor orci eu. Quisque sagittis purus sit amet volutpat consequat. Neque viverra justo nec ultrices. Ultrices dui sapien eget mi proin sed libero enim sed. Donec ac odio tempor orci dapibus. Nisl condimentum id venenatis a condimentum vitae sapien. Vitae aliquet nec ullamcorper sit amet. Feugiat vivamus at augue eget arcu dictum varius. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Congue eu consequat ac felis donec et odio. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc.",

  "In eu mi bibendum neque egestas congue quisque. Morbi tristique senectus et netus et malesuada fames. Sed turpis tincidunt id aliquet risus feugiat in ante. Diam phasellus vestibulum lorem sed risus ultricies. Felis imperdiet proin fermentum leo vel orci. Gravida quis blandit turpis cursus in hac. Neque gravida in fermentum et sollicitudin. Eget felis eget nunc lobortis mattis aliquam faucibus. Dolor purus non enim praesent elementum facilisis leo. Quis lectus nulla at volutpat diam ut venenatis. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Sed arcu non odio euismod lacinia at quis. Laoreet non curabitur gravida arcu ac. Id cursus metus aliquam eleifend mi in nulla. Sit amet nisl suscipit adipiscing bibendum. Arcu cursus euismod quis viverra nibh cras pulvinar mattis.",

  "Tincidunt dui ut ornare lectus sit amet est placerat. Tempor nec feugiat nisl pretium fusce id velit. Eget gravida cum sociis natoque. Non enim praesent elementum facilisis leo vel. Felis eget nunc lobortis mattis aliquam. Felis imperdiet proin fermentum leo vel orci porta. Pulvinar proin gravida hendrerit lectus. Sapien faucibus et molestie ac feugiat. Sit amet facilisis magna etiam tempor orci eu lobortis. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Duis convallis convallis tellus id. Scelerisque fermentum dui faucibus in ornare quam. Mauris cursus mattis molestie a iaculis at erat. Vitae semper quis lectus nulla at. Etiam sit amet nisl purus. Vel turpis nunc eget lorem dolor sed viverra ipsum. Nisl condimentum id venenatis a condimentum vitae sapien. Amet massa vitae tortor condimentum lacinia quis vel eros. Ac turpis egestas integer eget aliquet.",

  "Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Eu augue ut lectus arcu bibendum at varius vel pharetra. Hendrerit gravida rutrum quisque non tellus. Nullam non nisi est sit amet facilisis. In hendrerit gravida rutrum quisque non tellus orci. Imperdiet sed euismod nisi porta lorem mollis aliquam. At auctor urna nunc id. Et egestas quis ipsum suspendisse ultrices gravida dictum. Mattis aliquam faucibus purus in. Nibh tortor id aliquet lectus proin. Consectetur purus ut faucibus pulvinar elementum integer enim.",

  "Sed cras ornare arcu dui vivamus arcu felis bibendum. Quisque non tellus orci ac auctor augue mauris augue neque. Elit ut aliquam purus sit. Enim lobortis scelerisque fermentum dui faucibus in ornare. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Felis eget velit aliquet sagittis id consectetur purus. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Justo donec enim diam vulputate ut. Enim eu turpis egestas pretium. Adipiscing elit pellentesque habitant morbi. Mollis aliquam ut porttitor leo a. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a. Commodo nulla facilisi nullam vehicula. Felis donec et odio pellentesque diam volutpat commodo sed. Id nibh tortor id aliquet lectus proin. Bibendum ut tristique et egestas. Quisque sagittis purus sit amet volutpat consequat mauris nunc. Egestas diam in arcu cursus euismod quis. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis.?",
];

// console.log(texts);

const inputNumber = document.querySelector("#paragraph"),
  btnGenetare = document.querySelector(".btn-generate"),
  textContent = document.querySelector(".text-content");

btnGenetare.addEventListener("click", () => {
  // console.log(inputNumber.value);
  let value = parseInt(inputNumber.value);
  let random = Math.floor(Math.random() * texts.length);

  if (isNaN(value) || value < 0 || value > 25) {
    textContent.innerHTML = `
      <p class="text">${random}. ${texts[random]}</p>
    `;
  } else {
    let text = texts
      .slice(0, value)
      .map((item, index) => {
        return `<p class="text">${index + 1}. ${item}</p>`;
      })
      .join("");
    textContent.innerHTML = text;
  }
});
